aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: us-east-1
  s3:
    bucket:
        name: festivo-bucket
resend:
  api:
    key: ${RESEND_API_KEY}
api:
  email: contact@gustavoglins.com
  security:
    token:
      secret: ${PRIVATE_KEY}
      public: ${PUBLIC_KEY}
spring:
  application:
    name: festivo-api
  datasource:
    url: jdbc:postgresql://localhost:5432/db_festivo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: ${AWS_SES_USERNAME}
    password: ${AWS_SES_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
server:
  port: 8080
file:
  upload-dir: uploads